INSERT INTO artist(name) VALUES
	('Хелависа'),
	('Дмитрий Фролов'),
	('Сергей Седых'),
	('Курт Кобейн'),
	('Дэйв Грол'),
	('Владимир Холстинин'),
	('Валерий Кипелов'),
	('Канцлер Ги'),
	('Рустем Булатов');

INSERT INTO genre(name) VALUES
	('Фолк-рок'),
	('Арт-рок'),
	('Этно-фьюжн'),
	('Гранж'),
	('Сладж'),
	('Панк-рок'),
	('Хард-рок'),
	('Инди-рок'),
	('Альтернативный рок'),
	('Хеви-метал');

INSERT INTO album(name, creation_date) VALUES
	('Дикие травы', '21-02-2009'),
	('Зов крови', '01-12-2006'),
	('Открытый берег', '01-01-2008'),
	('Bleach', '15-07-1989'),
	('Nevermind', '24-09-1991'),
	('Проклятье морей', '13-11-2018'),
	('Весы Судьбы', '08-03-2024'),
	('Герой Асфальта', '01-09-1987'),
	('Тень на стене', '01-01-2008'),
	('Покажите Солнце', '01-07-2020');

INSERT INTO collection(name, creation_date) VALUES
	('The Best', '01-01-2007'),
	('Легенды русского рока - 2', '01-01-1997'),
	('Sliver: The Best of the Box', '01-11-2005'),
	('Легенды русского рока — 7', '01-01-2002'),
	('2.0','22-11-2019');

INSERT INTO track (id_album, name, duration) VALUES
	(1, 'Опасное лето', INTERVAL '4 minutes 24 seconds'),
	(1, 'Далеко', INTERVAL '4 minutes 10 seconds'),
	(1, 'Шелкопряд', INTERVAL '4 minutes 5 seconds'),
	(1, 'А если бы он...', INTERVAL '3 minutes 15 seconds'),
	(1, 'Ведьма', INTERVAL '3 minutes 50 seconds'),
	(1, 'Кувшин', INTERVAL '5 minutes 0 seconds'),
	(1, 'Княже', INTERVAL '3 minutes 45 seconds'),
	(1, 'Ветер', INTERVAL '3 minutes 20 seconds'),
	(1, 'Шаман', INTERVAL '4 minutes 50 seconds'),
	(1, 'Волкодав', INTERVAL '5 minutes 1 second'),
	(1, 'Ушба', INTERVAL '3 minutes 12 seconds'),
	(1, 'Океан', INTERVAL '4 minutes 11 seconds'),
	(2, 'Невеста Полоза', INTERVAL '4 minutes 33 seconds'),
	(2, 'Зов крови', INTERVAL '3 minutes 57 seconds'),
	(2, 'Двери Тамерлана', INTERVAL '3 minutes 29 seconds'),
	(2, 'Травушка', INTERVAL '3 minutes 54 seconds'),
	(2, 'Сестра', INTERVAL '3 minutes 32 seconds'),
	(2, 'Полнолуние', INTERVAL '4 minutes 10 seconds'),
	(2, 'Сказка о Дьяволе', INTERVAL '4 minutes 0 seconds'),
	(2, 'Дракон', INTERVAL '4 minutes 12 seconds'),
	(2, 'Ай, волна', INTERVAL '4 minutes 22 seconds'),
	(2, 'Ворожи', INTERVAL '4 minutes 20 seconds'),
	(2, 'Огонь', INTERVAL '3 minutes 50 seconds'),
	(2, 'Лента в волосах', INTERVAL '3 minutes 5 seconds'),
	(3, 'От неба до неба', INTERVAL '4 minutes 15 seconds'),
	(3, 'Улетаю', INTERVAL '3 minutes 50 seconds'),
	(3, 'В глубине материка', INTERVAL '4 minutes 1 second'),
	(3, 'Когда пройдет зима', INTERVAL '4 minutes 28 seconds'),
	(3, 'Предчувствие пути', INTERVAL '6 minutes 29 seconds'),
	(3, 'Чайка', INTERVAL '4 minutes 26 seconds'),
	(3, 'Линия воды', INTERVAL '3 minutes 58 seconds'),
	(4, 'Blew', INTERVAL '2 minutes 54 seconds'),
	(4, 'Floyd the Barber', INTERVAL '2 minutes 18 seconds'),
	(4, 'About a Girl', INTERVAL '2 minutes 48 seconds'),
	(4, 'School', INTERVAL '2 minutes 40 seconds'),
	(4, 'Love Buzz', INTERVAL '3 minutes 35 seconds'),
	(4, 'Paper Cuts', INTERVAL '2 minutes 45 seconds'),
	(4, 'Negative Creep', INTERVAL '2 minutes 56 seconds'),
	(4, 'Scoff', INTERVAL '2 minutes 27 seconds'),
	(4, 'Swap Meet', INTERVAL '2 minutes 20 seconds'),
	(4, 'Mr. Moustache', INTERVAL '3 minutes 23 seconds'),
	(4, 'Sifting', INTERVAL '5 minutes 22 seconds'),
	(5, 'Smells Like Teen Spirit', INTERVAL '5 minutes 1 second'),
	(5, 'In Bloom', INTERVAL '4 minutes 15 seconds'),
	(5, 'Come as You Are', INTERVAL '3 minutes 39 seconds'),
	(5, 'Breed', INTERVAL '3 minutes 3 seconds'),
	(5, 'Lithium', INTERVAL '4 minutes 17 seconds'),
	(5, 'Polly', INTERVAL '2 minutes 57 seconds'),
	(5, 'Territorial Pissings', INTERVAL '2 minutes 22 seconds'),
	(5, 'Drain You', INTERVAL '3 minutes 43 seconds'),
	(5, 'Lounge Act', INTERVAL '2 minutes 36 seconds'),
	(5, 'Stay Away', INTERVAL '3 minutes 32 seconds'),
	(5, 'On a Plain', INTERVAL '3 minutes 16 seconds'),
	(5, 'Something in the Way', INTERVAL '3 minutes 52 seconds'),
	(6, 'Проклятие морей', INTERVAL '5 minutes 55 seconds'),
	(6, 'Городская черепаха', INTERVAL '4 minutes 12 seconds'),
	(6, 'Улицы ветра', INTERVAL '6 minutes 5 seconds'),
	(6, 'Море и корабли', INTERVAL '5 minutes 35 seconds'),
	(6, 'Шторм', INTERVAL '7 minutes 12 seconds'),
	(6, 'Небо и земля', INTERVAL '4 minutes 50 seconds'),
	(6, 'Вперёд в бой', INTERVAL '3 minutes 48 seconds'),
	(7, 'Судьба', INTERVAL '5 minutes 10 seconds'),
	(7, 'Время', INTERVAL '4 minutes 30 seconds'),
	(7, 'Театр теней', INTERVAL '6 minutes 0 seconds'),
	(7, 'Путь', INTERVAL '5 minutes 45 seconds'),
	(7, 'Свобода', INTERVAL '4 minutes 40 seconds'),
	(7, 'Призыв', INTERVAL '5 minutes 20 seconds'),
	(8, 'Улица Роз', INTERVAL '5 minutes 56 seconds'),
	(8, '1100', INTERVAL '4 minutes 55 seconds'),
	(9, 'Барт мой, брат...', INTERVAL '3 minutes 3 seconds'),
	(10, 'Хороший царь и знакомая вонь', INTERVAL '3 minutes 21 seconds');

INSERT INTO album_artist(id_album, id_artist) VALUES 
	(1, 1),
	(1, 2),
	(1, 3),
	(2, 1),
	(2, 2),
	(3, 3), 
	(3, 1), 
	(4, 4), 
	(5, 4), 
	(5, 5), 
	(6, 6), 
	(7, 7),
	(8, 6),
	(8, 7),
	(9, 8),
	(10, 9);

INSERT INTO artist_genre (id_artist, id_genre) VALUES 
	(1, 1),
	(2, 2), 
	(2, 3),
	(3, 2), 
	(3, 3),
	(4, 4),
	(4, 5),
	(4, 6), 
	(4, 9),
	(5, 4), 
	(5, 5), 
	(5, 8),
	(6, 7), 
	(6, 10),
	(7, 7), 
	(7, 10),
	(8, 1),
	(8, 2),
	(9, 9),
	(9, 6);

INSERT INTO collection_track (id_collection, id_track) VALUES
	(1, 16), 
	(1, 23), 
	(1, 22), 
	(1, 18), 
	(1, 13),
	(2, 68),
	(3, 33), 
	(3, 34), 
	(3, 47), 
	(3, 43), 
	(3, 45),
	(4, 69),
	(5, 14), 
	(5, 2), 
	(5, 1);

